shinyUI(pageWithSidebar(
  headerPanel("学生成绩分析"),
  sidebarPanel(
    tags$h3("文件上传"),
    fileInput('file1', '选择文件',
              accept=c('text/csv', 'text/comma-separated-values,text/plain'), 
              buttonLabel = '浏览', placeholder = '没有选中文件'),
    tags$hr(),
    tags$h3("文件读取"),
    checkboxInput('show', '显示原表格', TRUE),
    checkboxInput('header', '显示表头', TRUE),
    radioButtons('sep', '分隔符',
                 c("逗号"=',',
                   "分号"=';',
                   "Tab"='\t'),
                 '逗号'),
    radioButtons('quote', '引号',
                 c("无"='',
                   '单引号'="'",
                   '双引号'='"'),
                 '双引号'),
    submitButton("重新导入"),
    tags$hr(),
    tags$h3("文件操作"),
    sliderInput("ave.range", "求平均值",
                min = 1, max = 20, value = c(1, 2)), 
    sliderInput("ove.range", "求大于等于某成绩的学生比率", 
                min = 1, max = 20, value = c(1, 2)), 
    numericInput("obs", "成绩大于等于", 60), 
    helpText("用滑条选择要计算的列"),
    submitButton("重新计算"),
    tags$hr(),
    tags$h3("统计分析"),
    tags$p("回归分析："),
    numericInput("yno", "因变量所在列", 1),
    numericInput("xno", "自变量所在列", 1), 
    tags$p("主成分分析："),
    sliderInput("pcano", "进行主成分分析的列", 
                min = 1, max = 20, value = c(1, 2)),
    submitButton("重新分析")
  ),
  mainPanel(
    tags$h3("平均值"),
    tableOutput('ave'),
    tags$h3(textOutput('text')),
    tableOutput('ove'),
    tags$h3("回归分析"),
    plotOutput('lmplot'),
    verbatimTextOutput('lmsummary'),
    tags$h3("主成分分析"),
    verbatimTextOutput('pcasummary'),
    tags$h3("原始数据"),
    tableOutput('contents')
  )
))